# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f035f7741be42240706d0a01643a2d984fb1ca5486fa1a97e5b1581d85aca1bcdd130c5b4e59a9d99745d18191ec224b11d58050a20997289fc95d8a6d545f2e

test:
  secret_key_base: 63026ac94d04dbc36a63a5033501b999662d57573c1a1f2ac435e6cb72fd9bede5de49d9ecb398a14a7d35ea522a43fdad1970034a6f28eb8013b4f63cb9562a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
